"""update table pagge_role and add relationship in role 

Revision ID: 1744d03eba19
Revises: 
Create Date: 2025-05-13 10:04:01.065171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1744d03eba19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'permission_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('permission_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
