"""add permission_name to pages

Revision ID: 9a9ffca29572
Revises: 1744d03eba19
Create Date: 2025-05-14 11:03:14.026056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9ffca29572'
down_revision: Union[str, None] = '1744d03eba19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_roles',
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name='page_roles_page_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='page_roles_role_id_fkey'),
    sa.PrimaryKeyConstraint('page_id', 'role_id', name='page_roles_pkey')
    )
    # ### end Alembic commands ###
